### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GlobbinTerpenes** [FiveEYZ/esx_kashacter#1]
i get an error when using the server side license edit

**Comment by GlobbinTerpenes** [comment]
![Capture](https://user-images.githubusercontent.com/59237450/82287506-60572e80-996e-11ea-94cf-f8b86f7a843c.PNG)

**Comment by FiveEYZ** [comment]
got all the `columns` in `users` table it selects in that query at line 90?

**Comment by GlobbinTerpenes** [comment]
![Capture](https://user-images.githubusercontent.com/59237450/82287988-7c0f0480-996f-11ea-8408-6e596a0674d6.PNG)
yeah

**Comment by GlobbinTerpenes** [comment]
i get as far as the esx_identity menu but it doesnt let me press enter i assume because this error

**Comment by FiveEYZ** [comment]
can u print the identifier and check what it uses to find data?

**Comment by GlobbinTerpenes** [comment]
do i do it like this ? print(identifier)

**Comment by FiveEYZ** [comment]
yea, u can add it on line 88

**Comment by FiveEYZ** [comment]
haven't had the time to test this in the latest master branch of es_extended and all the updates it has received the last few days.

**Comment by GlobbinTerpenes** [comment]
![Capture](https://user-images.githubusercontent.com/59237450/82288943-a06be080-9971-11ea-9013-06195142eaa4.PNG)
what 1 does it work on? could you link the commit incase i cant figure this out, i was using extended mode but couldnt get this to work so switched to the newest version of esx

**Comment by FiveEYZ** [comment]
https://github.com/ESX-Org/es_extended/tree/383aceffb408f17e6dad42aa08234a1e8b3d4453

**Comment by FiveEYZ** [comment]
how is the data saved in the database? (specifically the identifier in this case) 
did u have any data in the database before u added kashacters and edited es_extended?

**Comment by GlobbinTerpenes** [comment]
no it is a fresh database / server im still getting the same error with the version you linked 
![Capture](https://user-images.githubusercontent.com/59237450/82289970-ddd16d80-9973-11ea-832a-a62ff303613b.PNG)

**Comment by FiveEYZ** [comment]
and no data gets saved?

**Comment by GlobbinTerpenes** [comment]
the license saves in users but the error causes me not to be able to create an identity to get the rest of the info saved

**Comment by FiveEYZ** [comment]
done the edits in esx client? or does it happens after u press "create"?

**Comment by GlobbinTerpenes** [comment]
yeah i did all your edits, i spawn onto the kash spawn point and the esx menu pops up and that error at the same time, i can fill out the info but when i press enter nothing happens. i just created a character without kash installed and now will try and see if having some info helps

**Comment by GlobbinTerpenes** [comment]
yeah that didnt work lol same error

**Comment by FiveEYZ** [comment]
job and job_grade both have "default data", i dont really see how this error could happen :S

![](https://i.gyazo.com/922efb8720d84706a552b46132b023ea.png)

**Comment by GlobbinTerpenes** [comment]
yeah im at a loss im going to try an older esx_identity but i doubt thats it

**Comment by GlobbinTerpenes** [comment]
yeah still doesnt idk maybe ill give up for a lil, its strange it works for you and not me even using the same esx

**Comment by FiveEYZ** [comment]
maybe u can try the fork i based this one on, it just updated. might work

**Comment by GlobbinTerpenes** [comment]
i tried it lol it didnt work at all just sends character errors

**Comment by FiveEYZ** [comment]
this still boggles my mind, its like its trying to get data from the database before its supposed to...

try see if u can figure out whats triggering that function and when it does it.

and have u tried without kashacters? does everything work then?

**Comment by GlobbinTerpenes** [comment]
yeah without kash it works perfectectly fine,  with kash as soon as the camera comes down on my character and esx_identity opens it throws the error... with older esx identity i can click enter and itll make a character but not save the info in db

**Comment by GlobbinTerpenes** [comment]
so on a comletely fresh server with the newest esx_identity & esx_skin i get this error. but if i go back to older esx_identity and esx_skin it works

**Comment by GlobbinTerpenes** [comment]
this was with extendedmode set to rockstart licenses tho and not es_extended

**Comment by GlobbinTerpenes** [comment]
might of spoke 2 soon lol it saves characters but the skins dont load

**Comment by GlobbinTerpenes** [comment]
hey just to update you it was 100% the newest esx_identity causing my issue
