### ISSUE TITLE
Skin not loading apart from first time

### ISSUE THREAD

**Issue by charlesh9999** [FiveEYZ/esx_kashacter#13]
Hello, every time my character loads in it has no skin (apart from the first time when I set the character up)
Everything is saving and loading just fine with not a single error, so where is the code to set my characters model on reload I see SetDefaultModel but no where is my player skin set unless we walk to the clothes shop and do some shopping.

Have you got a snippet of code to put in to load the skin or does everyone just have to be default apart from the first time?...

**Comment by Leah-UK** [comment]
How did you fix this issue?
