### ISSUE TITLE
Issues with Registration and Customization

### ISSUE THREAD

**Issue by Leah-UK** [FiveEYZ/esx_kashacter#15]
I'm honestly not sure if this is an issue with Kashacter or with something else. However, while using the newest version of esx_identity and with Steam verification enabled it opens the "ESXIdentity Character Registration" menu on spawn, every time which disallows me to use Kash's own registration panel. How can I fix this? I've tried reverting the version (of esx_identity) and while that does fix this specific issue it creates other issues.
After this panel, it opens the customization screen but you cannot actually customize your character / press enter to continue.

**Comment by CarlBishop** [comment]
You should use the esx_identity linked in the readme

**Comment by Leah-UK** [comment]
Thank you very much, that seems to have solved my problem :) However, I still seem to spawn in invisible and am unable to customize / complete the character customization :( 

EDIT: I get the console error of script:skinchanger event skinchanger:loadDefaultModel was not safe for net.
EDIT2: Managed to get past the above issue. I can customize and save, seems to be added to the SQL correctly - however when spawning back in I start as Michael?

**Comment by CarlBishop** [comment]
I guess you have to find a working skinchanger. I was able to get I working, but only for 3 users. As soon as 5 or 6 users register on the server I have thousand of errors and nothing works any more.
![image](https://user-images.githubusercontent.com/12203647/85952442-9c1be580-b969-11ea-9ef2-4c400ae96de9.png)
I don't think this works good for esx 1.2

**Comment by Leah-UK** [comment]
Working as in the character models get set to the customized one on rejoin?
