### ISSUE TITLE
Some issues with Kashacters and the edited es_extended

### ISSUE THREAD

**Issue by Xorbite** [FiveEYZ/esx_kashacter#19]
Hello there,

I'm getting the following issues after implementing kashacters and after editing some parts of the code in es_extended, if u know the solution to those issues, please let know of it. The issues are: 

1. The server is not getting listed on the FiveM online servers list
2. When a player joins, the server won't recognize or detect that player and therefor the player won't show in the tab menu nor in the server.
3. Es_extended is not saving characters. When someone makes a character and leaves, it will not save the character that he created and therefore when he joins back, he would need to make a completely new character. 
4. Kashacters is not saving the player's data and characters.

I can't seem to find a solution for the problems that I'm getting and to be honest, I'm starting to give up after trying many solutions like uninstalling es_extended and reinstalling it back, installing an older version of esx_extended, installing a new version of es_extended or even installing the newest version of es_extended didn't really help. If you can help me I would really appreciate that. I really need kashacters implemented in my server as it is a roleplay server and it won't make sense for someone who wants to roleplay as a police officer and a criminal with the same name and description. He is my discord name: Estel#1999 incase If you want to add me on discord to talk more about the issues and how to solve them.

**Comment by xoptimus** [comment]
1 - this is due to you stopping spawnmanager and mapmanager in server.cfg (the solution to this is to put spawnmanager and mapmanager in, but open the files in notepad and delete all the text inside.
2 - this is probably due to this version using rockstar license, and you are using steam. You need to update es_extended and kashacters to use steam.
3 - related to issue 2
4 - related to issue 2
