### ISSUE TITLE
 The character selection menu doesn't always work

### ISSUE THREAD

**Issue by Persya2** [FiveEYZ/esx_kashacter#2]
Thank you for this great adaptation to the new esx.
it all works well only that sometimes the character selection menu does not appear when connecting, you have to reconnect often so that it works and appears.
could you help me further

**Comment by FiveEYZ** [comment]
hey and thanks for liking it.

could u try the latest commit and see if that fixes ur issue, and please try keep it in english :)

**Comment by Persya2** [comment]
Hello friend
I used the new customization.
But it still didn't work,
I fixed it by reading the line
56-57 changed

RegisterNetEvent ('kashactersC: SetupUI')
AddEventHandler ('kashactersC: SetupUI', function (Characters)
    DoScreenFadeIn (500)
    Citizen.Wait (500)
    SetNuiFocus (true, true)
    SendNUIMessage ({
        action = "openui",
        characters = characters,
    })
end)

replace to

RegisterNetEvent ('kashactersC: SetupUI')
AddEventHandler ('kashactersC: SetupUI', function (Characters)
    DoScreenFadeIn (2000)
    Citizen.Wait (2000)
    SetNuiFocus (true, true)
    SendNUIMessage ({
        action = "openui",
        characters = characters,
    })
end)

maybe I could help with it if it also happened to others

Thanks for the help and all the best
Thank you for your publication.
